"""extraction fields

Revision ID: 7fb663aca1b6
Revises: ab5494abf0b9
Create Date: 2025-08-12 21:47:29.070604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_users_db_sqlalchemy.generics import GUID


# revision identifiers, used by Alembic.
revision: str = '7fb663aca1b6'
down_revision: Union[str, Sequence[str], None] = 'ab5494abf0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('extraction_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('embedding_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("extraction_type IN ('table', 'diagram', 'statistic', 'text', 'other')", name='valid_extraction_type'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('extractions_status', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('extraction_started_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('extraction_completed_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('extraction_error', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extraction_summary', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'extraction_summary')
    op.drop_column('documents', 'extraction_error')
    op.drop_column('documents', 'extraction_completed_at')
    op.drop_column('documents', 'extraction_started_at')
    op.drop_column('documents', 'extractions_status')
    op.drop_table('extractions')
    # ### end Alembic commands ###
